version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: lumiere-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: lumiere
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: lumiere-redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: lumiere-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Trungdung.203@localhost:5432/lumiere
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: lumiere-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  pgdata: