"""add question field to Query

Revision ID: 3efca13b51ec
Revises: 5e83ab4f9c21
Create Date: 2025-11-21 09:39:49.787585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efca13b51ec'
down_revision = '5e83ab4f9c21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'connection_string',
               existing_type=sa.TEXT(),
               comment='Optional full DSN or file path',
               existing_comment='Optional full DSN',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'connection_string',
               existing_type=sa.TEXT(),
               comment='Optional full DSN',
               existing_comment='Optional full DSN or file path',
               existing_nullable=True)
    # ### end Alembic commands ###

