"""Add password reset fields to user model

Revision ID: 4c772b7ebe1d
Revises: 1fa2cf495087
Create Date: 2025-11-17 17:09:51.929127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c772b7ebe1d'
down_revision = '1fa2cf495087'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True, comment='Password reset token'))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(timezone=True), nullable=True, comment='Token expiration time'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Platform administrator flag',
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Platform administrator flag',
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###

